# CMake generated Testfile for 
# Source directory: C:/Users/me/pbrt/src/ext/ptex/src/tests
# Build directory: C:/Users/me/pbrt/src/ext/ptex/src/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(wtest "C:/Users/me/pbrt/src/ext/ptex/src/tests/Debug/wtest.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(wtest "C:/Users/me/pbrt/src/ext/ptex/src/tests/Release/wtest.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(wtest "C:/Users/me/pbrt/src/ext/ptex/src/tests/MinSizeRel/wtest.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(wtest "C:/Users/me/pbrt/src/ext/ptex/src/tests/RelWithDebInfo/wtest.exe")
else()
  add_test(wtest NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(rtest "C:/Program Files/CMake/bin/cmake.exe" "-DOUT=C:/Users/me/pbrt/src/ext/ptex/src/tests/rtest.out" "-DDATA=C:/Users/me/pbrt/src/ext/ptex/src/tests/rtestok.dat" "-DCMD=C:/Users/me/pbrt/src/ext/ptex/src/tests/Debug/rtest.exe" "-P" "C:/Users/me/pbrt/src/ext/ptex/src/tests/compare_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(rtest "C:/Program Files/CMake/bin/cmake.exe" "-DOUT=C:/Users/me/pbrt/src/ext/ptex/src/tests/rtest.out" "-DDATA=C:/Users/me/pbrt/src/ext/ptex/src/tests/rtestok.dat" "-DCMD=C:/Users/me/pbrt/src/ext/ptex/src/tests/Release/rtest.exe" "-P" "C:/Users/me/pbrt/src/ext/ptex/src/tests/compare_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(rtest "C:/Program Files/CMake/bin/cmake.exe" "-DOUT=C:/Users/me/pbrt/src/ext/ptex/src/tests/rtest.out" "-DDATA=C:/Users/me/pbrt/src/ext/ptex/src/tests/rtestok.dat" "-DCMD=C:/Users/me/pbrt/src/ext/ptex/src/tests/MinSizeRel/rtest.exe" "-P" "C:/Users/me/pbrt/src/ext/ptex/src/tests/compare_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(rtest "C:/Program Files/CMake/bin/cmake.exe" "-DOUT=C:/Users/me/pbrt/src/ext/ptex/src/tests/rtest.out" "-DDATA=C:/Users/me/pbrt/src/ext/ptex/src/tests/rtestok.dat" "-DCMD=C:/Users/me/pbrt/src/ext/ptex/src/tests/RelWithDebInfo/rtest.exe" "-P" "C:/Users/me/pbrt/src/ext/ptex/src/tests/compare_test.cmake")
else()
  add_test(rtest NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(ftest "C:/Program Files/CMake/bin/cmake.exe" "-DOUT=C:/Users/me/pbrt/src/ext/ptex/src/tests/ftest.out" "-DDATA=C:/Users/me/pbrt/src/ext/ptex/src/tests/ftestok.dat" "-DCMD=C:/Users/me/pbrt/src/ext/ptex/src/tests/Debug/ftest.exe" "-P" "C:/Users/me/pbrt/src/ext/ptex/src/tests/compare_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(ftest "C:/Program Files/CMake/bin/cmake.exe" "-DOUT=C:/Users/me/pbrt/src/ext/ptex/src/tests/ftest.out" "-DDATA=C:/Users/me/pbrt/src/ext/ptex/src/tests/ftestok.dat" "-DCMD=C:/Users/me/pbrt/src/ext/ptex/src/tests/Release/ftest.exe" "-P" "C:/Users/me/pbrt/src/ext/ptex/src/tests/compare_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(ftest "C:/Program Files/CMake/bin/cmake.exe" "-DOUT=C:/Users/me/pbrt/src/ext/ptex/src/tests/ftest.out" "-DDATA=C:/Users/me/pbrt/src/ext/ptex/src/tests/ftestok.dat" "-DCMD=C:/Users/me/pbrt/src/ext/ptex/src/tests/MinSizeRel/ftest.exe" "-P" "C:/Users/me/pbrt/src/ext/ptex/src/tests/compare_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(ftest "C:/Program Files/CMake/bin/cmake.exe" "-DOUT=C:/Users/me/pbrt/src/ext/ptex/src/tests/ftest.out" "-DDATA=C:/Users/me/pbrt/src/ext/ptex/src/tests/ftestok.dat" "-DCMD=C:/Users/me/pbrt/src/ext/ptex/src/tests/RelWithDebInfo/ftest.exe" "-P" "C:/Users/me/pbrt/src/ext/ptex/src/tests/compare_test.cmake")
else()
  add_test(ftest NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(halftest "C:/Users/me/pbrt/src/ext/ptex/src/tests/Debug/halftest.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(halftest "C:/Users/me/pbrt/src/ext/ptex/src/tests/Release/halftest.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(halftest "C:/Users/me/pbrt/src/ext/ptex/src/tests/MinSizeRel/halftest.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(halftest "C:/Users/me/pbrt/src/ext/ptex/src/tests/RelWithDebInfo/halftest.exe")
else()
  add_test(halftest NOT_AVAILABLE)
endif()
